#!/usr/bin/env bash

function main {
	local pkgdest=${1:-"/"}
	local pkgname=${2:-"arch-pkgs-tools"}
	install -Dm755 ./src/init.bash "$pkgdest"/usr/bin/ap-init
	install -Dm755 ./src/new-pkg.bash "$pkgdest"/usr/bin/ap-new-pkg
	install -Dm755 ./src/pkg.bash "$pkgdest"/usr/bin/ap-pkg
	install -Dm755 ./src/debug.bash "$pkgdest"/usr/bin/ap-debug
	install -Dm755 ./src/get-aur.bash "$pkgdest"/usr/bin/ap-get-aur
	install -Dm755 ./src/test.bash "$pkgdest"/usr/bin/ap-test
	install -Dm644 ./src/ap-tools.conf "$pkgdest"/etc/ap-tools.conf
	install -Dm644 ./docker-build/Dockerfile "$pkgdest"/usr/share/ap-tools/Dockerfile
	install -Dm644 ./docker-build/build.bash "$pkgdest"/usr/share/ap-tools/build
	install -Dm644 ./LICENSE "$pkgdest"/usr/share/licenses/"$pkgname"/LICENSE
}

main $@
